
[target]
; From /dev/by-partuuid
;kernel_part_uuid=BA0A4C89-E60C-1F41-8873-4A215DA30A9B
kernel_part_uuid=8a6ebc63-dcbc-3e47-9de6-4d8508e0115e
; From /dev/by-uuid
root_uuid=eff7d75b-98d9-45da-ba8a-469cde11db12

[build]
; Choose one of these, not both. defconfig builds from an existing defconfig,
; whereas config_file points to a config file that will used verbatim
defconfig=kevin_defconfig
;config_file=<path to config file>

; For the kernel build command; required
kernel_arch=arm64
cross_compile=aarch64-linux-gnu-
jobs=8

; vbutil_kernel arguments, optional
vbutil_kernel=vbutil_kernel
keyblock=resources/gru-kevin/kernel.keyblock
data_key=resources/gru-kevin/kernel_data_key.vbprivk
; cmdline=console=tty1 console=ttyS2,115200n8 earlyprintk=ttyS2,115200n8 init=/sbin/init root=PARTUUID=%U/PARTNROFF=1 rootwait rw noinitrd
cmdline=console=tty1 console=ttyS2,115200n8 earlyprintk=ttyS2,115200n8 init=/sbin/init root=PARTUUID=BA0A4C89-E60C-1F41-8873-4A215DA30A9B/PARTNROFF=1 rootwait rw noinitrd no_console_suspend=1
vbutil_arch=aarch64

; mkimage arguments, optional
mkimage=mkimage
its_file=resources/gru-kevin/rk3399-gru-kevin.its

; post-build options
;install_modules=yes
;install_dtbs=yes
install_modules=no
install_dtbs=no
generate_htmldocs=no

