// SPDX-License-Identifier: GPL-2.0-only
/*
 * Definitions for rVIC/rVID PV interrupt controller architecture.
 *
 * Copyright 2020 Google LLC.
 * Author: Marc Zyngier <maz@kernel.org>
 *
 * WARNING: All these constants are subject to change until the spec is final.
 */

#ifndef __IRQCHIP_IRQ_RVIC_H__
#define __IRQCHIP_IRQ_RVIC_H__

#include <linux/bitfield.h>

/* Versioning */
#define RVIx_VERSION_MAJOR_MASK		GENMASK(31, 16)
#define RVIx_VERSION_MINOR_MASK		GENMASK(15, 0)

#define RVIx_VERSION(M, m)				\
	(FIELD_PREP(RVIx_VERSION_MAJOR_MASK, (M)) |	\
	 FIELD_PREP(RVIx_VERSION_MINOR_MASK, (m)))

#define RVIx_VERSION_MAJOR(v)		FIELD_GET(RVIx_VERSION_MAJOR_MASK, (v))
#define RVIx_VERSION_MINOR(v)		FIELD_GET(RVIx_VERSION_MINOR_MASK, (v))

/* Error reporting */
#define RVIx_STATUS_REASON_MASK		GENMASK(7, 0)
#define RVIx_STATUS_INDEX_MASK		GENMASK(15, 8)

#define RVIx_STATUS_PACK(r,i)				\
	(FIELD_PREP(RVIx_STATUS_REASON_MASK, (r)) |	\
	 FIELD_PREP(RVIx_STATUS_INDEX_MASK, (i)))

#define RVIx_STATUS_REASON(c)		FIELD_GET(RVIx_STATUS_REASON_MASK, (c))
#define RVIx_STATUS_INDEX(c)		FIELD_GET(RVIx_STATUS_INDEX_MASK, (c))

#define RVIx_STATUS_SUCCESS		0
#define RVIx_STATUS_ERROR_PARAMETER	1
#define RVIx_STATUS_INVALID_CPU		2
#define RVIx_STATUS_DISABLED		3
#define RVIx_STATUS_NO_INTERRUPTS	4

/* rVIC functions */
#define SMC64_RVIC_BASE			0xc5000200
#define SMC64_RVIC_FN(n)		(SMC64_RVIC_BASE + (n))

#define SMC64_RVIC_VERSION		SMC64_RVIC_FN(0)
#define SMC64_RVIC_INFO			SMC64_RVIC_FN(1)
#define SMC64_RVIC_ENABLE		SMC64_RVIC_FN(2)
#define SMC64_RVIC_DISABLE		SMC64_RVIC_FN(3)
#define SMC64_RVIC_SET_MASKED		SMC64_RVIC_FN(4)
#define SMC64_RVIC_CLEAR_MASKED		SMC64_RVIC_FN(5)
#define SMC64_RVIC_IS_PENDING		SMC64_RVIC_FN(6)
#define SMC64_RVIC_SIGNAL		SMC64_RVIC_FN(7)
#define SMC64_RVIC_CLEAR_PENDING	SMC64_RVIC_FN(8)
#define SMC64_RVIC_ACKNOWLEDGE		SMC64_RVIC_FN(9)
#define SMC64_RVIC_RESAMPLE		SMC64_RVIC_FN(10)

#define SMC64_RVIC_LAST			SMC64_RVIC_RESAMPLE

#define RVIC_INFO_KEY_NR_TRUSTED_INTERRUPTS	0
#define RVIC_INFO_KEY_NR_UNTRUSTED_INTERRUPTS	1

#define RVIC_VERSION(M, m)		RVIx_VERSION((M), (m))

#define RVIC_VERSION_MAJOR(v)		RVIx_VERSION_MAJOR((v))
#define RVIC_VERSION_MINOR(v)		RVIx_VERSION_MINOR((v))

#define RVIC_STATUS_REASON(c)		RVIx_STATUS_REASON((c))
#define RVIC_STATUS_INDEX(c)		RVIx_STATUS_INDEX((c))

#define RVIC_STATUS_SUCCESS		RVIx_STATUS_SUCCESS
#define RVIC_STATUS_ERROR_PARAMETER	RVIx_STATUS_ERROR_PARAMETER
#define RVIC_STATUS_INVALID_CPU		RVIx_STATUS_INVALID_CPU
#define RVIC_STATUS_DISABLED		RVIx_STATUS_DISABLED
#define RVIC_STATUS_NO_INTERRUPTS	RVIx_STATUS_NO_INTERRUPTS

/* rVID functions */
#define SMC64_RVID_BASE			0xc5000100
#define SMC64_RVID_FN(n)		(SMC64_RVID_BASE + (n))

#define SMC64_RVID_VERSION		SMC64_RVID_FN(0)
#define SMC64_RVID_MAP			SMC64_RVID_FN(1)
#define SMC64_RVID_UNMAP		SMC64_RVID_FN(2)

#define SMC64_RVID_LAST			SMC64_RVID_UNMAP

#define RVID_VERSION(M, m)		RVIx_VERSION((M), (m))

#define RVID_VERSION_MAJOR(v)		RVIx_VERSION_MAJOR((v))
#define RVID_VERSION_MINOR(v)		RVIx_VERSION_MINOR((v))

#define RVID_STATUS_REASON(c)		RVIx_STATUS_REASON((c))
#define RVID_STATUS_INDEX(c)		RVIx_STATUS_INDEX((c))

#define RVID_STATUS_SUCCESS		RVIx_STATUS_SUCCESS
#define RVID_STATUS_ERROR_PARAMETER	RVIx_STATUS_ERROR_PARAMETER

#endif /* __IRQCHIP_IRQ_RVIC_H__ */
